name: CI
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        # execute every 12 hours
        - cron: '0 */12 * * *'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch: {}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    update-submodules:
        runs-on: ubuntu-latest
        steps:
        # every time a commit happens to a submodule, the main repo will be updated
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Update submodules
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "github@actions.com"
            git submodule add --force https://github.com/CECRI23/blog-cms src/content/blog
            git submodule add --force https://github.com/CECRI23/blog-cms public/documents
            git submodule sync
            git submodule update --recursive --remote
            git add .
            git commit -m "Update submodules"
            git push